### ISSUE TITLE
Surface field SCALAR or COLOR_SCALAR data that results in stagger being cell

### ISSUE THREAD

**Issue by gregvonkuster** [gregvonkuster/galaxy-csg#11]
@pletzer Do we have a data file that results in the value of 'stagger' being 'cell' in the following snippet of code from cg.mako?
        var stagger = 'point';
        if ( colors.length == indices.length ) {
            stagger = 'cell';
        }
I tried several things, but I could not provide data that resulted in stagger being cell, so could not test the downstream code.

I even tried hard-coding "stagger = 'cell' and viewing a shape to which I added a surface field with location = 'cell', but that threw an exception.

**Comment by pletzer** [comment]
Hi Greg,

See attachment. Thanks for testing.

--Alex

On Fri, Oct 30, 2015 at 12:28 PM, Greg Von Kuster notifications@github.com
wrote:

> @pletzer https://github.com/pletzer Do we have a data file that results
> in the value of 'stagger' being 'cell' in the following snippet of code
> from cg.mako?
> var stagger = 'point';
> if ( colors.length == indices.length ) {
> stagger = 'cell';
> }
> I tried several things, but I could not provide data that resulted in
> stagger being cell, so could not test the downstream code.
> 
> I even tried hard-coding "stagger = 'cell' and viewing a shape to which I
> added a surface field with location = 'cell', but that threw an exception.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gregvonkuster/galaxy-csg/issues/11.

## 

Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
@pletzer I don't think the attachment made it into your comment above (at least I don't see it).  Can you try again?

**Comment by pletzer** [comment]
Attaching again... Let me know if you didn't get it.

On Mon, Nov 2, 2015 at 8:30 AM, Greg Von Kuster notifications@github.com
wrote:

> @pletzer https://github.com/pletzer I don't think the attachment made
> it into your comment above (at least I don't see it). Can you try again?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gregvonkuster/galaxy-csg/issues/11#issuecomment-153053148
> .

## 

Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
@pletzer I still don't see it.  Can you see it in your above comment?  Your view should be the same as mine.  How are you attempting to attach the file?
