### ISSUE TITLE
Latest version of csg.mako has bugs

### ISSUE THREAD

**Issue by gregvonkuster** [gregvonkuster/galaxy-csg#16]
The shapes are no longer centered in the camera view. When I view a shape, I see blank space and have to move the camera randomly in order to find the shape. It is also no longer possible to rotate or spin the shape using the mouse when the shape is within the camera view.

**Comment by pletzer** [comment]
If you create a box with X = 100, Y = 200, and Z = 300 at origin. Do you still see the problem? The box shows centered for me. Make sure to update to the latest.

--Alex

**Comment by gregvonkuster** [comment]
I am no longer seeing this behavior as of this change: https://github.com/gregvonkuster/galaxy-csg/commit/3c4172fd5c9938b031859e1475ee4e58bf588dc6
