### ISSUE TITLE
Selecting texture image does not work

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#23]
@gregvonkuster  When selecting "add texture image to shape surface" the field "no jpg or png file dataset available" does not seem to be active despite the fact that I uploaded a jpeg file. The file is called IMG_0742.JPG. 

It does not look like jpg, jpeg, JPEG, JPG, PNG, or png are among the supported file types to be uploaded (?)

How can upload a texture file? 

Thanks.

--Alex

**Comment by gregvonkuster** [comment]
@pletzer All of the image formats that you listed can be uploaded.  When you click to open the history item of the image you uploaded, what is the displayed format?  It should display this:
format  jpg   database?

**Comment by pletzer** [comment]
Hi Greg,

I'm not sure I understand what I should do.

I'm wondering if I got rid of some critical functionality when installing
galaxy-csg on http://galaxy-pedees.rhcloud.com/.

If you connect to http://galaxy-pedees.rhcloud.com/ you should see CSG and
Get data among the tools. I can upload a jpg file when I select "Upload
file from your computer". When I do this I see the attached window.

My problem is that in the middle pane, I cannot select the image file under
"Texture image". It says no jpg or png dataset available.

I don't find the JPG file on the openshift server, it looks like it has
never been uploaded. Where should these files go?

[galaxy-pedees.rhcloud.com galaxy]> cat config/tool_conf.xml

<?xml version='1.0' encoding='utf-8'?>

<toolbox>

  <section id="getext" name="Get Data">

```
<tool file="data_source/upload.xml" />
```

  </section>

  <section id="csg" name="CSG">

```
<tool file="csg/icqsol_create_shape.xml" />

<tool file="csg/icqsol_translate_shape.xml" />

<tool file="csg/icqsol_rotate_shape.xml" />

<tool file="csg/icqsol_scale_shape.xml" />

<tool file="csg/icqsol_compose_shapes.xml" />

<tool file="csg/icqsol_add_texture.xml" />

<tool file="csg/icqsol_add_surface_field_from_expression.xml" />

<tool file="csg/icqsol_color_surface_field.xml" />
```

  </section>

</toolbox>

Thanks.

--Alex

On Sat, Dec 12, 2015 at 9:30 AM, Greg Von Kuster notifications@github.com
wrote:

> @pletzer https://github.com/pletzer All of the image formats that you
> listed can be uploaded. When you click to open the history item of the
> image you uploaded, what is the displayed format? It should display this:
> format jpg database?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gregvonkuster/galaxy-csg/issues/23#issuecomment-164165687
> .

## 

Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by pletzer** [comment]
Hi Greg,

I recreated config/tools_conf.xml, keeping all other tools and now I'm able
to upload the file. Problem solved.

--Alex

On Sun, Dec 13, 2015 at 9:25 AM, Alexander Pletzer alexander@gokliya.net
wrote:

> Hi Greg,
> 
> I'm not sure I understand what I should do.
> 
> I'm wondering if I got rid of some critical functionality when installing
> galaxy-csg on http://galaxy-pedees.rhcloud.com/.
> 
> If you connect to http://galaxy-pedees.rhcloud.com/ you should see CSG
> and Get data among the tools. I can upload a jpg file when I select "Upload
> file from your computer". When I do this I see the attached window.
> 
> My problem is that in the middle pane, I cannot select the image file
> under "Texture image". It says no jpg or png dataset available.
> 
> I don't find the JPG file on the openshift server, it looks like it has
> never been uploaded. Where should these files go?
> 
> [galaxy-pedees.rhcloud.com galaxy]> cat config/tool_conf.xml
> 
> <?xml version='1.0' encoding='utf-8'?>
> 
> <toolbox>
> 
>   <section id="getext" name="Get Data">
> 
> ```
> <tool file="data_source/upload.xml" />
> ```
> 
>   </section>
> 
>   <section id="csg" name="CSG">
> 
> ```
> <tool file="csg/icqsol_create_shape.xml" />
> 
> <tool file="csg/icqsol_translate_shape.xml" />
> 
> <tool file="csg/icqsol_rotate_shape.xml" />
> 
> <tool file="csg/icqsol_scale_shape.xml" />
> 
> <tool file="csg/icqsol_compose_shapes.xml" />
> 
> <tool file="csg/icqsol_add_texture.xml" />
> 
> <tool file="csg/icqsol_add_surface_field_from_expression.xml" />
> 
> <tool file="csg/icqsol_color_surface_field.xml" />
> ```
> 
>   </section>
> 
> </toolbox>
> 
> Thanks.
> 
> --Alex
> 
> On Sat, Dec 12, 2015 at 9:30 AM, Greg Von Kuster <notifications@github.com
> 
> > wrote:
> > 
> > @pletzer https://github.com/pletzer All of the image formats that you
> > listed can be uploaded. When you click to open the history item of the
> > image you uploaded, what is the displayed format? It should display this:
> > format jpg database?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gregvonkuster/galaxy-csg/issues/23#issuecomment-164165687
> > .
> 
> ## 
> 
> Alexander Pletzer
> +1 609 799 7999 cell
> alexander@gokliya.net

## 

Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
@pletzer can this issue be closed?

**Comment by pletzer** [comment]
Still flaky... I'm getting a seg fault with a cylinder with an excavated cone...

/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/job_working_directory/000/31/tool_script.sh: line 2: 131996 Segmentation fault      (core dumped) python /var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/tools/csg/icqsol_add_texture.py --input "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_28.dat" --input_file_format_and_type vtkascii --input_dataset_type POLYDATA --input_texture "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_29.dat" --input_texture_file_format jpg --output "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_33.dat" --output_vtk_type vtkascii

**Comment by pletzer** [comment]
The selection works however, so closing...
