### ISSUE TITLE
Recommend "Add texture to shape" instead of "Add texture image to a shape surface"

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#24]
@gregvonkuster 
It's implicitly known that texture is added to a surface. No need to say "image". No need for article "a.

**Comment by gregvonkuster** [comment]
Fixed here https://github.com/gregvonkuster/galaxy-csg/commit/36c62fd691108fc56a0b277c915e5f464c181877, thanks!
