### ISSUE TITLE
Colors don't seem to be plotted

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#25]
@gregvonkuster reported that the texture does not show up.

**Comment by gregvonkuster** [comment]
@pletzer Can you clarify this issue?  Is this the same issue as this: https://github.com/pletzer/icqsol/issues/45?

**Comment by pletzer** [comment]
@gregvonkuster This has been fixed in icqsol. The problem was that polydata.GetPointData().AddArray(rbgArray) was used instead of polydata.GetPointData().SetScalars(rbgArray). In the former case, a field is created (FIELD FieldData numFieldds) whereas in the latter a COLOR_SCALARS field of type POINT_DATA is created. VTKLoader.js only supports the former. 

A FIELD is more flexible than COLOR_SCALARS -- multiple fields can be added. However, this flexibility is not required for colors (there can only be one color on the surface of the shape).
