### ISSUE TITLE
Need to click twice on the Visualize -> CSG viewer

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#26]
@gregvonkuster Anytime I'm visualizing (selecting Visualize -> CSG viewer) I need to press twice. The first time I get the GUI controls showing up but no scene. See attachment. 
![screen shot 2015-12-13 at 9 48 44 am](https://cloud.githubusercontent.com/assets/3027118/11768064/ce048bb8-a17e-11e5-8136-cafd32a1f74a.png)

**Comment by gregvonkuster** [comment]
This is due to some Galaxy Javascript bug.  It is not in our control.
