### ISSUE TITLE
Error when selecting png file for texture

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#27]
@gregvonkuster Selecting a png file for texture does not work

I created a default box and uploaded the png file
![testbolt](https://cloud.githubusercontent.com/assets/3027118/11768321/72fc7322-a186-11e5-88fa-a6602bd79252.png)

Then I add texture to shape using a max edge length of 10 and I get the following error, which suggests that jpeg reader was used in place of the png reader. 

--Alex

ERROR: In /var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/vtklite/VTK-6.3.0/IO/Image/vtkJPEGReader.cxx, line 174
vtkJPEGReader (0x268d730): libjpeg could not read file: /var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_90.dat

ERROR: In /var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/vtklite/VTK-6.3.0/IO/Image/vtkJPEGReader.cxx, line 357
vtkJPEGReader (0x268d730): libjpeg could not read file: /var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/database/files/000/dataset_90.dat

Traceback (most recent call last):
  File "/var/lib/openshift/5611ccc02d52713b6000010c/app-root/data/source/galaxy/tools/csg/icqsol_add_texture.py", line 38, in <module>
    vtk_poly_data = shape_mgr.addTextureToVtkPolyData(vtk_poly_data, texture_file=args.input_texture, max_edge_length=max_edge_length)
  File "build/bdist.linux-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 215, in addTextureToVtkPolyData
TypeError: SetTuple argument 2: expected a sequence of 3 values, got 1 values

**Comment by gregvonkuster** [comment]
@pletzer there is a mess of code that has to create a temporary file with a specific extension because the ShapeManager.addTextureToVtkPolyData() function will not accept an optional image format.  The code would be so much simpler if you would agree to add format=None to the method signature.  Then all of this complexity could be eliminated.

**Comment by pletzer** [comment]
@gregvonkuster I added the keyword texture_file_format to 

```
def addTextureToVtkPolyData(self, vtk_poly_data,
                            texture_file,
                            max_edge_length=float('inf'),
                            texture_file_format=''):
```

in ShapeManager. If texture_file_format is not specified then the format will be inferred from the suffix.

**Comment by gregvonkuster** [comment]
@pletzer I've simplified the icqsol_add_texture tool to pass the texture_file_format parameter to ShapeManager.addTextureToVtkPolyData.  But even without that change, I was not seeing this behavior.  I have been uploading png files and applying them as texture for a while now.  Make sure you are using the latest version of the tool.

**Comment by pletzer** [comment]
Fixed.
