### ISSUE TITLE
Refinement is broken when adding texture 

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#28]
@gregvonkuster After creating a default box, uploading the below image, and selecting a Maximum edge length of 0.01
![swietenia_macrophylla_wood](https://cloud.githubusercontent.com/assets/3027118/11768346/8bee369e-a187-11e5-8ff5-e52dcf648e0d.jpg)

I get 
![screen shot 2015-12-13 at 10 54 12 am](https://cloud.githubusercontent.com/assets/3027118/11768363/ec2878da-a187-11e5-8215-b016d00e2e40.png)

The resolution is way too coarse. Indeed, I can see that there are only 24 triangles suggesting that the shape was not refined. 
# vtk DataFile Version 4.0

vtk output
ASCII
DATASET POLYDATA
POINTS 24 float
0 0 0 0 0 1 0 1 1 
0 1 0 1 0 0 1 1 0 
1 1 1 1 0 1 0 0 0 
0 0 0 0 0 1 0 0 1 
0 1 1 0 1 1 0 1 0 
0 1 0 1 0 0 1 0 0 
1 1 0 1 1 0 1 1 1 
1 1 1 1 0 1 1 0 1 

POLYGONS 12 48
3 3 0 1 
3 1 2 3 
3 7 4 5 
3 5 6 7 
3 10 8 16 
3 16 22 10 
3 18 14 12 
3 12 20 18 
3 17 9 15 
3 15 19 17 
3 13 11 23 
3 23 21 13 

POINT_DATA 24
COLOR_SCALARS Colors 3
0.8 0.486275 0.286275 0.87451 0.639216 0.427451 0.847059 0.607843 0.396078 
0.643137 0.356863 0.231373 0.505882 0.298039 0.172549 
0.737255 0.435294 0.270588 0.737255 0.431373 0.180392 
0.682353 0.372549 0.219608 0.8 0.486275 0.286275 
0.8 0.486275 0.286275 0.87451 0.639216 0.427451 
0.87451 0.639216 0.427451 0.847059 0.607843 0.396078 
0.847059 0.607843 0.396078 0.643137 0.356863 0.231373 
0.643137 0.356863 0.231373 0.505882 0.298039 0.172549 
0.505882 0.298039 0.172549 0.737255 0.435294 0.270588 
0.737255 0.435294 0.270588 0.737255 0.431373 0.180392 
0.737255 0.431373 0.180392 0.682353 0.372549 0.219608 
0.682353 0.372549 0.219608 
NORMALS Normals float
-1 0 0 -1 0 0 -1 0 0 
-1 0 0 1 0 0 1 0 0 
1 0 0 1 0 0 0 -1 0 
0 0 -1 0 -1 0 0 0 1 
0 1 0 0 0 1 0 1 0 
0 0 -1 0 -1 0 0 0 -1 
0 1 0 0 0 -1 0 1 0 
0 0 1 0 -1 0 0 0 1

**Comment by pletzer** [comment]
@gregvonkuster It looks like the gui entry does not take the maximum edge length value. If I hardwire this value in icqsol_add_texture.py:

vtk_poly_data = shape_mgr.addTextureToVtkPolyData(vtk_poly_data, texture_file=args.input_texture, max_edge_length=0.01)

I get 

![screen shot 2015-12-13 at 11 15 50 am](https://cloud.githubusercontent.com/assets/3027118/11768477/1f7d211a-a18b-11e5-817e-a69522ba7cb7.png)

**Comment by gregvonkuster** [comment]
@pletzer I'm not seeing this behavior.  Make sure you are running the latest version of the tool.  I get the following image, and the dataset size is 8902915.

<img width="327" alt="texture" src="https://cloud.githubusercontent.com/assets/6947053/11798744/8d9a940a-a29b-11e5-98bb-b8f83b9cccd1.png">

**Comment by pletzer** [comment]
Should be fixed now...
