### ISSUE TITLE
Need pycsg 0.3.x

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#32]
@gregvonkuster My pull request sent to the author of pycsg has not yet been accepted. This puts us in a conundrum since we rely on officially released versions on pip, the latest version there being 0.2. 

Our possibilities are:
- Provide a recipe that pulls the code from our repo
- Save the project under a different name (e.g. pycsg-galaxy) and have icqsol depend on it
- ?

**Comment by gregvonkuster** [comment]
I would say the 2nd option is the most optimal.  At some point we'll need to formally define a release URL for icqsol, so however it is pulling in dependencies like this must be such that a specific URL for icqsol will ensure reproducible behavior for the package features.

**Comment by pletzer** [comment]
Fixed in setup.py script of icqsol. The latest version of pycsg gets pulled in:

[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import csg
> > > print csg.**version**
> > > 0.3.3
