### ISSUE TITLE
subtracting a cone from a box fails

### ISSUE THREAD

**Issue by pletzer** [gregvonkuster/galaxy-csg#34]
@gregvonkuster Create a default box then subtract a default cone and you might get:

Traceback (most recent call last):
  File "/home/alexander/galaxy/tools/csg/icqsol_compose_shapes.py", line 18, in <module>
    shape_mgr = icqsol_utils.get_shape_manager()
TypeError: get_shape_manager() takes exactly 2 arguments (0 given)

I tried on google cloud (http://146.148.44.114:8080/) running the latest version of everything. I don't get the problem on openshift (http://galaxy-pedees.rhcloud.com/) (?)

**Comment by pletzer** [comment]
@gregvonkuster It seems that ShapeManager() was replaced by get_shape_manager(), which expects two arguments. Setting default values for these to None fixes the issue.

**Comment by gregvonkuster** [comment]
@pletzer This regression should be fixed in https://github.com/gregvonkuster/galaxy-csg/commit/2d622ad11121aa19173bc7d3c84652ea69da5fcf
