### ISSUE TITLE
add_surface_field_from_expression tool broken

### ISSUE THREAD

**Issue by gregvonkuster** [gregvonkuster/galaxy-csg#7]
@pletzer This change seems to have broken the add_surface_field_from_expression tool:
https://github.com/gregvonkuster/galaxy-csg/commit/d24e0c06d92b1a60bf7a7a30c80f5c11cffa2f42

Using the attached file as the input (the file is a vtk data file but I had to change the extension to allow it to be uploaded here) 
[box.txt](https://github.com/gregvonkuster/galaxy-csg/files/12444/box.txt)
dataset along with these parameter values:

field_name: surface_field
expression: (x**2 \* sin(y*pi) + z**4) \* exp(t)
time_point: 0.1

produces the following output:

/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqRefineSurface.py:91: RuntimeWarning: divide by zero encountered in double_scalars
  numSegs = int(max(1, math.ceil(edgeLength/max_edge_length)))
Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_surface_field_from_expression/cc17f560a6e7/icqsol_add_surface_field_from_expression/icqsol_add_surface_field_from_expression.py", line 40, in <module>
    args.max_edge_length)
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py", line 143, in addSurfaceFieldFromExpressionToShape
    max_edge_length=max_edge_length)
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py", line 249, in refineVtkPolyData
    rs.refine(max_edge_length=max_edge_length)
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqRefineSurface.py", line 91, in refine
    numSegs = int(max(1, math.ceil(edgeLength/max_edge_length)))
OverflowError: cannot convert float infinity to integer

**Comment by pletzer** [comment]
Hi Greg,

Please update galaxy-csg. Let me know if the change did not fix the issue.
Thanks.

--Alex

On Tue, Oct 13, 2015 at 6:31 AM, Greg Von Kuster notifications@github.com
wrote:

> This change seems to have broken the add_surface_field_from_expression
> tool:
> d24e0c0
> https://github.com/gregvonkuster/galaxy-csg/commit/d24e0c06d92b1a60bf7a7a30c80f5c11cffa2f42
> 
> Using the attached file as the input (the file is a vtk data file but I
> had to change the extension to allow it to be uploaded here)
> box.txt https://github.com/gregvonkuster/galaxy-csg/files/12444/box.txt
> dataset along with these parameter values:
> 
> field_name: surface_field
> expression: (x_2 \* sin(y_pi) + z*4) \* exp(t)
> time_point: 0.1
> 
> produces the following output:
> 
> /Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqRefineSurface.py:91:
> RuntimeWarning: divide by zero encountered in double_scalars
> numSegs = int(max(1, math.ceil(edgeLength/max_edge_length)))
> Traceback (most recent call last):
> File
> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_surface_field_from_expression/cc17f560a6e7/icqsol_add_surface_field_from_expression/icqsol_add_surface_field_from_expression.py",
> line 40, in
> args.max_edge_length)
> File
> "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py",
> line 143, in addSurfaceFieldFromExpressionToShape
> max_edge_length=max_edge_length)
> File
> "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py",
> line 249, in refineVtkPolyData
> rs.refine(max_edge_length=max_edge_length)
> File
> "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/2e903d73018b/lib/python2.7/site-packages/icqsol/shapes/icqRefineSurface.py",
> line 91, in refine
> numSegs = int(max(1, math.ceil(edgeLength/max_edge_length)))
> OverflowError: cannot convert float infinity to integer
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gregvonkuster/galaxy-csg/issues/7.

## 

Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
@pletzer Fixed with this change: 
https://github.com/gregvonkuster/galaxy-csg/commit/6ffa7b953a5c15fc739a2365ffc795a0093b79b3
Thanks!
